# -*- coding: utf-8 -*-
"""demo_app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12GatURjuk865lvPvLcf5S_hrktHtBilw
"""

import streamlit as st
import cv2
import numpy as np
from PIL import Image
import face_recognition
from streamlit_drawable_canvas import st_canvas

from vision_utils import load_yolo_model, encode_face

st.set_page_config(page_title="GateKeeper AI", layout="wide")
st.title("🛡️ GateKeeper AI: Enterprise Security")


if "known_encodings" not in st.session_state:
    st.session_state.known_encodings = []
if "known_names" not in st.session_state:
    st.session_state.known_names = []
if "restricted_zone" not in st.session_state:
    st.session_state.restricted_zone = None

model = load_yolo_model()


tab1, tab2, tab3 = st.tabs(["👤 1. Face Enrollment", "📐 2. Setup Zone", "🚨 3. Live Monitor"])

# ==========================================
# TAB 1: FACE ENROLLMENT
# ==========================================
with tab1:
    st.header("Register Authorized Personnel")
    col1, col2 = st.columns(2)

    with col1:
        emp_name = st.text_input("Employee Name:")

        uploaded_file = st.file_uploader("Upload Face Image", type=["jpg", "jpeg", "png"])

        if st.button("Register Face") and uploaded_file is not None and emp_name:

            encodings = encode_face(uploaded_file)

            if len(encodings) > 0:
                st.session_state.known_encodings.append(encodings[0])
                st.session_state.known_names.append(emp_name)
                st.success(f"Successfully registered: {emp_name}")
            else:
                st.error("No face detected in the image. Try a clearer picture.")

    with col2:
        st.write("### Authorized Database")
        if len(st.session_state.known_names) > 0:
            for name in st.session_state.known_names:
                st.info(f"✅ {name}")
        else:
            st.warning("No employees registered yet.")

# ==========================================
# TAB 2: ZONE SETUP
# ==========================================
with tab2:
    st.header("Draw the Restricted Perimeter")
    st.write("Draw a rectangle over the camera feed to define the secure zone.")

    cap = cv2.VideoCapture(0) # Change to "test_demo.mp4" if testing on video
    ret, frame = cap.read()
    cap.release()

    if ret:
        frame_rgb = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
        bg_image = Image.fromarray(frame_rgb)

        canvas_result = st_canvas(
            fill_color="rgba(255, 0, 0, 0.3)",  # Transparent Red
            stroke_width=3,
            stroke_color="#FF0000",
            background_image=bg_image,
            drawing_mode="rect",
            height=frame_rgb.shape[0],
            width=frame_rgb.shape[1],
            key="canvas",
        )

        # Save coordinates to session state when drawn
        if canvas_result.json_data is not None and len(canvas_result.json_data["objects"]) > 0:
            box = canvas_result.json_data["objects"][-1] # Get latest drawn box
            x1, y1 = int(box["left"]), int(box["top"])
            x2, y2 = int(box["left"] + box["width"]), int(box["top"] + box["height"])

            st.session_state.restricted_zone = np.array([
                [x1, y1], [x2, y1], [x2, y2], [x1, y2]
            ], dtype=np.int32)
            st.success("Zone saved successfully!")
    else:
        st.error("Could not access camera for zone setup.")

# ==========================================
# TAB 3: LIVE MONITOR (YOLO + Face Rec)
# ==========================================
with tab3:
    st.header("Live Security Feed")

    if st.session_state.restricted_zone is None:
        st.warning("Please setup the restricted zone in Tab 2 first!")
    else:
        run_camera = st.checkbox("Start Live Monitoring")
        frame_window = st.image([])

        if run_camera:
            cap = cv2.VideoCapture(0)

            while run_camera:
                ret, frame = cap.read()
                if not ret:
                    st.error("Failed to grab frame.")
                    break

                # Draw the restricted zone on the frame
                cv2.polylines(frame, [st.session_state.restricted_zone], True, (0, 255, 255), 2)

                results = model(frame, stream=True, verbose=False)

                for result in results:
                    for box in result.boxes:
                        if int(box.cls[0]) == 0 and float(box.conf[0]) > 0.5: # Person detected
                            x1, y1, x2, y2 = map(int, box.xyxy[0])
                            foot_point = (int((x1 + x2) / 2), y2)


                            is_inside = cv2.pointPolygonTest(st.session_state.restricted_zone, foot_point, False) >= 0

                            label = "Person"
                            box_color = (255, 0, 0) # Default Blue for people outside

                            if is_inside:

                                face_crop = frame[max(0, y1):int(y1+(y2-y1)/2), max(0, x1):x2]
                                rgb_crop = cv2.cvtColor(face_crop, cv2.COLOR_BGR2RGB)

                                face_locations = face_recognition.face_locations(rgb_crop)
                                face_encs = face_recognition.face_encodings(rgb_crop, face_locations)

                                name = "UNKNOWN"
                                if len(face_encs) > 0 and len(st.session_state.known_encodings) > 0:
                                    matches = face_recognition.compare_faces(st.session_state.known_encodings, face_encs[0], tolerance=0.5)
                                    if True in matches:
                                        first_match_index = matches.index(True)
                                        name = st.session_state.known_names[first_match_index]

                                if name == "UNKNOWN":
                                    label = "🚨 INTRUDER"
                                    box_color = (0, 0, 255) # Red
                                    cv2.putText(frame, "BREACH DETECTED", (50, 50), cv2.FONT_HERSHEY_SIMPLEX, 1.5, (0, 0, 255), 3)
                                else:
                                    label = f"✅ Authorized: {name}"
                                    box_color = (0, 255, 0) # Green


                            cv2.rectangle(frame, (x1, y1), (x2, y2), box_color, 2)
                            cv2.circle(frame, foot_point, 6, box_color, -1)
                            cv2.putText(frame, label, (x1, y1 - 10), cv2.FONT_HERSHEY_SIMPLEX, 0.6, box_color, 2)


                frame = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
                frame_window.image(frame)

            cap.release()