# -*- coding: utf-8 -*-
"""vision_utils

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kjyKo3CAG9q5aM2b50w6aUvNKM-6rP_o
"""

import streamlit as st
import face_recognition
from ultralytics import YOLO

@st.cache_resource
def load_yolo_model():
    return YOLO("yolov8n.pt")

def encode_face(uploaded_file):
    image = face_recognition.load_image_file(uploaded_file)
    encodings = face_recognition.face_encodings(image)
    if len(encodings) > 0:
        return encodings[0]
    return None